sudo: required
branches:
  only:
   - master
services:
- docker

addons:
  apt:
    packages:
    - p7zip-full

before_script:
- docker build . -t wups-loader-builder
script:
- docker run -it --rm -v ${PWD}:/project wups-loader-builder make
before_deploy:
- cd $TRAVIS_BUILD_DIR/
- mkdir -p "wiiu/apps/wiiupluginloader"
- commit="$(git rev-parse --short=7 HEAD)"
- chmod +x gitrev.sh
- versiontag="$(./gitrev.sh)"
- docker run -it --rm -v ${PWD}:/project wups-loader-builder make
- cp meta/* wiiu/apps/wiiupluginloader
- cp wiiupluginloader.elf wiiu/apps/wiiupluginloader
- zip -r WiiUPluginLoader_$versiontag.zip wiiu

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key:
        secure: BVbhRaNdlbVsK1jfQ7rWUFE3wgTHlKhjovkr+Ti0HsxxjKzpkf9aDdylBh+EUgiGfMonkcsSgazb0biRygLUHoLuy6xe2rEbdFvDP1dwsEryRvR766FOqCPQ+KH1NzB0+Yq5FGyzg5A+c03vMTQqDz0vMKpRLv9tQr46rbCN5f3vsqEM3GhHnf9c9CxuM8Ui/A8sLiqXuzn8nL95QQKlO6N4iCWacC1qKinvwAoXvuLcocri7BiVzvUezy6yNOOB2v0zOGoxxRzMiImppyuPFdjpmtA8kR/Bs7VhBjvEmaS7U5kwDuPgrdnzZKr/0k5damRE0vjUQ0qhrL8gWNw5Bbe1A0kqRdCjqK+MRc3mZn+CcULjytZZ89UTbc0CgbqKTOrohzh+rxOQZ35MpnEz0D9CbOZ6FrAhxK1USzF5YivVKl8Sp8R77vCbuvwgGpPXVep0AD+0h0A7JPNpNjZPoGcQs2DS3k+TApqM1jYFOV3JkJIUFRAOcWUeg5WciBJyNtqXeKZmWkgQohsA7MLD+M3suvrnXs9IB9Ajyk7bejPdahS5nh3GRSGhUlGp0Lv9TXaOECG2/lYX1sPg//IQcTl8K+Uc0OkP5qpbIuE3GVNPmLlMTbm4ZqSYW9lO2Bacoz2oN/ggs+/JvU9DaMqsCY16FQsYYpOvK83wEWNpPeY=
  file: WiiUPluginLoader_$versiontag.zip
  on:
    repo: aboood40091/WiiUPluginLoader